### ISSUE TITLE
user .local install

### ISSUE THREAD

**Issue by Arnaudv6** [WayfireWM/wf-install#1]
Hello @ammen99, I'm so excited about this script, thanks!
I should like to install created bins in ~/.local/bin without the "sudo".
Is it something you would fancy please?

**Comment by ammen99** [comment]
I'll add a check to disable sudo when the user has write permissions for the prefix directory, this should be enough, right?

**Comment by ammen99** [comment]
@Arnaudv6 Does http://ix.io/2eW4 help?

**Comment by Arnaudv6** [comment]
Greeaaat! I now benefit from all the components instead of the half-assed solution I got the motivation to assemble earlier.

I only had to add "export" statement on
`export LD_LIBRARY_PATH=...`
in start_wayfire.sh for it to launch.

Again, thanks, this script helps me a lot.
I will try to adapt my [waypiedock](https://gitlab.com/Arnaudv6/waypiedock) to wayfire. Is there an ipc, or anyway to get a listing of launched windows?
Thanks!

**Comment by ammen99** [comment]
I have been thinking about the export, but left it since it seemed that it was working locally ... I'll add it though.

Wayfire supports https://github.com/swaywm/wlr-protocols/blob/master/unstable/wlr-foreign-toplevel-management-unstable-v1.xml so you can use it to list and control launched windows.
